"""add_invoice_items_table

Revision ID: 07cc3c421205
Revises: 66904d0c3c1d
Create Date: 2025-11-21 09:33:50.205770
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '07cc3c421205'
down_revision = '66904d0c3c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
