"""add_vehicle_inventory_and_fields

Revision ID: 1a3b981f5ac0
Revises: 5c90d446162d
Create Date: 2025-11-22 19:16:49.502820
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a3b981f5ac0'
down_revision = '5c90d446162d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customer_tenant_name', 'customers', ['tenant_id', 'name'])
    op.add_column('vehicles', sa.Column('van_number', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('chassis_number', sa.String(length=64), nullable=True))
    op.add_column('vehicles', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'purchase_date')
    op.drop_column('vehicles', 'chassis_number')
    op.drop_column('vehicles', 'van_number')
    op.drop_constraint('uq_customer_tenant_name', 'customers', type_='unique')
    # ### end Alembic commands ###
