"""add_subscription_fields_to_tenant_and_subscription_plan_model

Revision ID: 3baef85f285b
Revises: c452e854ca8d
Create Date: 2025-11-22 10:47:10.586256
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3baef85f285b'
down_revision = 'c452e854ca8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('features', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.alter_column('inventory_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tenants', sa.Column('plan_id', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('tenants', sa.Column('subscription_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('subscription_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('vehicles', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('vehicles', 'vin',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               nullable=True)
    op.alter_column('vehicles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_vehicles_vin'), 'vehicles', ['vin'], unique=False)
    op.drop_constraint(op.f('vehicles_customer_id_fkey'), 'vehicles', type_='foreignkey')
    op.create_foreign_key(None, 'vehicles', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.create_foreign_key(op.f('vehicles_customer_id_fkey'), 'vehicles', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vehicles_vin'), table_name='vehicles')
    op.alter_column('vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vehicles', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('vehicles', 'vin',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('vehicles', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'subscription_end')
    op.drop_column('tenants', 'subscription_start')
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'plan_id')
    op.alter_column('invoices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
