"""Add image_url to inventory_items

Revision ID: 5c90d446162d
Revises: dae9f4e14f36
Create Date: 2025-11-22 13:18:06.218331
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5c90d446162d'
down_revision = 'dae9f4e14f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'image_url')
    # ### end Alembic commands ###
