"""add_feature_flags_table

Revision ID: dae9f4e14f36
Revises: 3baef85f285b
Create Date: 2025-11-22 11:56:21.826235
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'dae9f4e14f36'
down_revision = '3baef85f285b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_feature_code'), 'feature_flags', ['feature_code'], unique=False)
    op.create_index(op.f('ix_feature_flags_tenant_id'), 'feature_flags', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feature_flags_tenant_id'), table_name='feature_flags')
    op.drop_index(op.f('ix_feature_flags_feature_code'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
